# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0002_auto_20160223_1001'),
    ]

    operations = [
    ]
