# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0004_auto_20160223_1315'),
    ]

    operations = [
    ]
