# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0005_auto_20160229_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invite',
            old_name='invite_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='invite',
            name='last_name',
            field=models.CharField(default='Last', max_length=200),
            preserve_default=False,
        ),
    ]
