# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0006_auto_20160313_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invite',
            old_name='group_number',
            new_name='group_count',
        ),
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default=b'3886', max_length=6),
        ),
    ]
