# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 13:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0007_auto_20160313_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='name',
            new_name='guest_name',
        ),
        migrations.RenameField(
            model_name='invite',
            old_name='first_name',
            new_name='group_name',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default=b'6114', max_length=6),
        ),
        migrations.AlterField(
            model_name='invite',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
