# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0009_auto_20160321_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default=b'6646', max_length=6),
        ),
    ]
