# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0010_auto_20160321_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='rsvp_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guest',
            name='diet',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default=b'6000', max_length=6),
        ),
    ]
