# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0013_auto_20160417_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='diet',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default=b'9819', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
