# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0014_auto_20160422_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='attending',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guest',
            name='diet',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default=b'8022', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='rsvp_completed',
            field=models.NullBooleanField(default=False, editable=False),
        ),
    ]
