# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-20 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0016_auto_20160425_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default=None, max_length=6, unique=True),
        ),
    ]
