# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-05 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0017_auto_20160520_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default='8232', max_length=6, unique=True),
        ),
    ]
