# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-05 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0018_auto_20160905_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default='9626', max_length=6, unique=True),
        ),
    ]
