# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-06 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0019_auto_20160905_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='actual',
            field=models.CharField(choices=[('exact', 'Exact'), ('similar', 'Similar')], default='exact', max_length=2),
        ),
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default='0457', max_length=6, unique=True),
        ),
    ]
