# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-06 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0020_auto_20160906_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default='0311', max_length=6, unique=True),
        ),
    ]
