# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-06 12:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0022_auto_20160906_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='', regex='^\\+?1?\\d{9,15}$')])),
                ('google_link', models.URLField(blank=True)),
                ('website_link', models.URLField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default='2662', max_length=6, unique=True),
        ),
    ]
