# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-06 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0023_auto_20160906_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='postcode',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default='2431', max_length=6, unique=True),
        ),
    ]
