# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-06 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0025_auto_20160906_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default='6501', max_length=6, unique=True),
        ),
    ]
