# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-06 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingapp', '0026_auto_20160906_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='actual',
            field=models.CharField(blank=True, choices=[('exact', 'Exact'), ('similar', 'Similar')], default='exact', max_length=200),
        ),
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(default='2512', max_length=6, unique=True),
        ),
    ]
